"use server";
import {and,desc,eq,sql} from "drizzle-orm";
import {randomUUID} from "node:crypto";
import {revalidatePath} from "next/cache";
import {z} from "zod";
import {getDb} from "@/db";
import {auditLogs,businessRecords,customers,financeTransactions,products,tasks,usdTransactions,websites} from "@/db/schema";
import {requireSession} from "@/lib/auth";
import {consume,recharge,averageCost,profit} from "@/lib/finance";

const text=(min=1,max=300)=>z.string().trim().min(min).max(max);
const money=(value:FormDataEntryValue|null)=>{const n=Number(value);if(!Number.isFinite(n)||n<0)throw new Error("金额格式错误");return Math.round(n*100)};
const when=(value:FormDataEntryValue|null)=>{const d=value?new Date(String(value)):new Date();if(Number.isNaN(d.getTime()))throw new Error("时间格式错误");return d};
async function audit(action:string,entityType:string,entityId:string){const s=await requireSession();await getDb().insert(auditLogs).values({workspaceId:s.workspaceId,userId:s.userId,action,entityType,entityId})}

export async function createCustomer(data:FormData){const s=await requireSession();const p=z.object({name:text(1,120),phone:z.string().trim().max(32),wechat:z.string().trim().max(80),notes:z.string().trim().max(1000)}).parse(Object.fromEntries(data));const [row]=await getDb().insert(customers).values({workspaceId:s.workspaceId,...p}).returning({id:customers.id});await audit("create","customer",row.id);revalidatePath("/customers")}
export async function createBusiness(data:FormData){const s=await requireSession();const p=z.object({customerId:z.string().uuid().optional().or(z.literal("")),type:z.enum(["membership","account","physical","service","other"]),content:text(1,500),status:z.enum(["pending_payment","paid_pending","processing","completed","after_sale","refunded"]),occurredAt:z.string().optional()}).parse(Object.fromEntries(data));const revenue=money(data.get("revenue"));const rawCost=String(data.get("cost")??"").trim();const cost=rawCost===""?null:money(rawCost);const direct=money(data.get("directExpense")??"0");const number=`YW${new Date().toISOString().replace(/\D/g,"").slice(0,17)}${randomUUID().slice(0,4)}`;const db=getDb();const [row]=await db.transaction(async tx=>{const inserted=await tx.insert(businessRecords).values({number,workspaceId:s.workspaceId,customerId:p.customerId||null,type:p.type,content:p.content,status:p.status,occurredAt:when(p.occurredAt??null),revenueCents:revenue,costCents:cost,directExpenseCents:direct,profitCents:profit(revenue,cost,direct)}).returning({id:businessRecords.id});if(revenue>0)await tx.insert(financeTransactions).values({workspaceId:s.workspaceId,businessId:inserted[0].id,type:"customer_receipt",occurredAt:new Date(),amountCents:revenue,notes:p.content});return inserted});await audit("create","business",row.id);revalidatePath("/business");revalidatePath("/dashboard")}
export async function createTask(data:FormData){const s=await requireSession();const p=z.object({title:text(1,200),dueAt:z.string().optional()}).parse(Object.fromEntries(data));const [row]=await getDb().insert(tasks).values({workspaceId:s.workspaceId,title:p.title,dueAt:p.dueAt?when(p.dueAt):null}).returning({id:tasks.id});await audit("create","task",row.id);revalidatePath("/tasks");revalidatePath("/dashboard")}
export async function toggleTask(data:FormData){const s=await requireSession();const id=z.string().uuid().parse(data.get("id"));const done=data.get("done")==="1";await getDb().update(tasks).set({completedAt:done?null:new Date(),updatedAt:new Date()}).where(and(eq(tasks.id,id),eq(tasks.workspaceId,s.workspaceId)));await audit(done?"reopen":"complete","task",id);revalidatePath("/tasks");revalidatePath("/dashboard")}
export async function createProduct(data:FormData){const s=await requireSession();const p=z.object({name:text(1,160),type:z.enum(["membership","account","physical","service","other"]),category:z.string().trim().max(100)}).parse(Object.fromEntries(data));const [row]=await getDb().insert(products).values({workspaceId:s.workspaceId,...p,defaultPriceCents:money(data.get("price")??"0"),defaultCostCents:money(data.get("cost")??"0"),safetyStock:Number(data.get("safetyStock")??0)}).returning({id:products.id});await audit("create","product",row.id);revalidatePath("/products")}
export async function createWebsite(data:FormData){const s=await requireSession();const p=z.object({name:text(1,120),url:z.url(),kind:z.enum(["self","third_party"]),notes:z.string().trim().max(500)}).parse(Object.fromEntries(data));const [row]=await getDb().insert(websites).values({workspaceId:s.workspaceId,...p}).returning({id:websites.id});await audit("create","website",row.id);revalidatePath("/websites")}
export async function createFinance(data:FormData){const s=await requireSession();const p=z.object({type:z.enum(["operating_expense","purchase","refund","other_income","other_expense"]),notes:z.string().trim().max(500),occurredAt:z.string().optional()}).parse(Object.fromEntries(data));const [row]=await getDb().insert(financeTransactions).values({workspaceId:s.workspaceId,type:p.type,occurredAt:when(p.occurredAt??null),amountCents:money(data.get("amount")),notes:p.notes}).returning({id:financeTransactions.id});await audit("create","finance",String(row.id));revalidatePath("/finance");revalidatePath("/dashboard")}
export async function createUsd(data:FormData){const s=await requireSession();const type=z.enum(["recharge","consume"]).parse(data.get("type"));const usd=z.coerce.number().positive().parse(data.get("usd"));const db=getDb();await db.transaction(async tx=>{await tx.execute(sql`select pg_advisory_xact_lock(hashtext(${s.workspaceId}))`);const [last]=await tx.select().from(usdTransactions).where(eq(usdTransactions.workspaceId,s.workspaceId)).orderBy(desc(usdTransactions.id)).limit(1);const pool={usd:Number(last?.balanceUsd??0),costCents:last?.balanceCostCents??0};if(type==="recharge"){const cost=money(data.get("cny"));const next=recharge(pool,usd,cost);await tx.insert(usdTransactions).values({workspaceId:s.workspaceId,type,occurredAt:new Date(),usdAmount:String(usd),cnyAmountCents:cost,balanceUsd:String(next.usd),balanceCostCents:next.costCents,averageCost:String(averageCost(next))})}else{const result=consume(pool,usd);await tx.insert(usdTransactions).values({workspaceId:s.workspaceId,type,occurredAt:new Date(),usdAmount:String(-usd),cnyAmountCents:result.costCents,balanceUsd:String(result.pool.usd),balanceCostCents:result.pool.costCents,averageCost:String(averageCost(result.pool))})}});await audit("create",`usd_${type}`,s.workspaceId);revalidatePath("/finance");revalidatePath("/dashboard")}
