"use client";
import {useMemo,useState} from "react";
import {Bell,BookOpen,Boxes,BriefcaseBusiness,CalendarCheck,ChevronDown,CircleDollarSign,Clock3,CreditCard,ExternalLink,FileChartColumn,Globe2,LayoutDashboard,Menu,PackageCheck,Plus,Search,Settings,Sparkles,TrendingUp,Users,WalletCards,X} from "lucide-react";

const nav=[["工作台",LayoutDashboard],["快速记录",Sparkles],["客户管理",Users],["业务流水",BriefcaseBusiness],["会员充值",CreditCard],["商品与库存",Boxes],["账号交付",PackageCheck],["资金流水",WalletCards],["经营报表",FileChartColumn],["待办提醒",CalendarCheck],["常用网站",Globe2],["系统设置",Settings]] as const;
const metrics=[["收款","¥ 2,680.00","较昨日 +18.6%",CircleDollarSign],["业务成本","¥ 946.40","已核算 8 笔",WalletCards],["经营支出","¥ 128.00","共 2 笔支出",CreditCard],["已核算利润","¥ 1,605.60","利润率 59.9%",TrendingUp]] as const;
const records=[["YW20260906008","张三","ChatGPT Plus 续费","会员充值","¥180.00","¥142.60","已完成","16:38:25"],["YW20260906007","李明","AI 软件安装服务","服务","¥300.00","¥300.00","办理中","15:22:10"],["YW20260906006","王姐","Claude Pro 成品号","账号产品","¥260.00","¥118.00","已完成","13:45:08"],["YW20260906005","赵先生","海外流量卡","实物产品","¥180.00","¥60.00","已付款待办理","11:12:42"]];
export default function Home(){const[active,setActive]=useState("工作台"),[mobile,setMobile]=useState(false),[quick,setQuick]=useState(""),[preview,setPreview]=useState(false);const today=useMemo(()=>new Intl.DateTimeFormat("zh-CN",{dateStyle:"full"}).format(new Date()),[]);return <div className="shell">
<aside className={mobile?"side open":"side"}><div className="brand"><i><BookOpen/></i><div><b>经营工作台</b><small>个人版 · 第一工作空间</small></div></div><nav>{nav.map(([n,I])=><button key={n} className={active===n?"active":""} onClick={()=>{setActive(n);setMobile(false)}}><I/><span>{n}</span>{n==="待办提醒"&&<em>5</em>}</button>)}</nav><div className="user"><span>林</span><div><b>林先生</b><small>管理员</small></div><ChevronDown/></div></aside>{mobile&&<button className="scrim" onClick={()=>setMobile(false)}/>}<main><header><button className="hamb" onClick={()=>setMobile(true)}><Menu/></button><label className="search"><Search/><input placeholder="搜索客户、业务、商品…"/><kbd>⌘ K</kbd></label><button className="bell"><Bell/></button><button className="primary"><Plus/>新建业务</button></header>
<div className="content"><section className="welcome"><div><h1>下午好，林先生</h1><p>{today} · 今天已有 8 笔业务</p></div><div className="tabs"><b>今天</b><span>本周</span><span>本月</span></div></section>
<section className="quick"><i><Sparkles/></i><div><b>快速记录</b><textarea value={quick} onChange={e=>setQuick(e.target.value)} placeholder="试试：今天16:38给张三的 test@example.com 续费 ChatGPT Plus 一个月，使用20美元，收180元。"/><footer><small>系统只会生成预览，确认后才写入账目</small><button disabled={!quick.trim()} onClick={()=>setPreview(true)}>识别并预览 ↵</button></footer></div></section>
{preview&&<div className="modal-wrap"><button className="backdrop" onClick={()=>setPreview(false)}/><section className="modal"><button className="close" onClick={()=>setPreview(false)}><X/></button><small>AI 识别预览</small><h2>请确认业务信息</h2><p>“{quick}”</p><div className="preview">{[["业务类型","会员充值"],["客户","张三"],["收款金额","¥180.00"],["消耗美元","$20.00"]].map(x=><label key={x[0]}>{x[0]}<b>{x[1]}</b></label>)}</div><aside>成本将在确认时按当前美元移动平均成本计算。</aside><footer><button onClick={()=>setPreview(false)}>返回修改</button><button className="primary" onClick={()=>{setPreview(false);setQuick("")}}>确认记录</button></footer></section></div>}
<section className="metrics">{metrics.map(([n,v,d,I],x)=><article key={n}><i className={`m${x}`}><I/></i><span>{n}</span><b>{v}</b><small>{d}</small></article>)}</section>
<div className="cols"><section className="panel"><Head title="待办与提醒" sub="需要你关注的事项" action="查看全部"/>{[[Clock3,"2 笔业务待办理","最早一笔已等待 3 小时"],[CalendarCheck,"3 个会员即将到期","未来 7 天内到期"],[Boxes,"2 个商品库存不足","已低于安全库存"]].map(([I,a,b],x)=><div className="todo" key={String(a)}><i className={`t${x}`}><I/></i><div><b>{String(a)}</b><small>{String(b)}</small></div><em>去处理</em></div>)}</section><section className="panel"><Head title="美元资金" sub="移动加权平均成本" action="资金明细"/><div className="usd"><small>当前美元余额</small><b>$ 286.50</b><span>对应人民币成本 ¥2,041.76</span></div><div className="usdrow">{[["平均成本","¥7.1266/USD"],["今日消耗","$40.00"],["今日充值","$100.00"]].map(x=><div key={x[0]}><small>{x[0]}</small><b>{x[1]}</b></div>)}</div></section></div>
<section className="panel table"><Head title="最近业务流水" sub="实时汇总每一笔经营业务" action="查看全部"/><div><table><thead><tr>{["业务编号","客户","业务内容","类型","收款","利润","状态","时间"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{records.map(r=><tr key={r[0]}>{r.map((x,i)=><td key={i}>{i===6?<span className="status">{x}</span>:x}</td>)}</tr>)}</tbody></table></div></section>
<div className="cols lower"><section className="panel"><Head title="库存概览" sub="当前可售库存" action="库存管理"/>{[["ChatGPT Plus 成品号",12],["Claude Pro 成品号",3],["海外流量卡",8]].map(([n,v])=><div className="stock" key={n}><label><b>{n}</b><small>{v} 件可用</small></label><div><i style={{width:`${Number(v)*5}%`}}/></div></div>)}</section><section className="panel"><Head title="常用网站" sub="快速访问经营工具" action="管理网站"/><div className="sites">{[["书","数字书库","自建网站"],["邮","NIMAIL","自建网站"],["AI","ChatGPT","第三方网站"]].map(x=><a key={x[1]} href={x[1]==="ChatGPT"?"https://chatgpt.com":"#"}><i>{x[0]}</i><div><b>{x[1]}</b><small>{x[2]}</small></div><ExternalLink/></a>)}</div></section></div></div></main></div>}
function Head({title,sub,action}:{title:string;sub:string;action:string}){return <header className="phead"><div><h2>{title}</h2><p>{sub}</p></div><button>{action}</button></header>}
